spring:
  application:
    name: Matchings

  datasource:
    url: "jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}?currentSchema=${DB_SCHEMA}"
    username: "${DB_USERNAME}"
    password: "${DB_PASSWORD}"
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: "${JPA_DDL_AUTO}"
    show-sql: true

jwt:
  secret: "${JWT_SECRET}"
